### ISSUE TITLE
recurring error

### ISSUE THREAD

**Issue by Benoulimou** [mjwwit/node-red-contrib-ikea-tradfri#20]
I saw this error passed but I can not find the discussion anymore.

I have this error all the time:

`Invalid message received, using node config!
Invalid value "binary_sensor.detecteur_etage_occupancy" supplied to : TradfriLightControlMessage/0: Partial<{ topic: (Int | Array<Int>), payload: TradfriLightControlAction }>/topic: (Int | Array<Int>)/0: Int
Invalid value "binary_sensor.detecteur_etage_occupancy" supplied to : TradfriLightControlMessage/0: Partial<{ topic: (Int | Array<Int>), payload: TradfriLightControlAction }>/topic: (Int | Array<Int>)/1: Array<Int>
Invalid value "Off" supplied to : TradfriLightControlMessage/0: Partial<{ topic: (Int | Array<Int>), payload: TradfriLightControlAction }>/payload: TradfriLightControlAction`

thx

**Comment by mjwwit** [comment]
From what I can see you're passing messages like this to the light-control-node:
```jsonc
{
  "topic": "binary_sensor.detecteur_etage_occupancy",
  "payload": "Off"
}
```

This node is expecting messages like:
```jsonc
{
  "topic": 12345, // The instance ID of the light you're trying to control
  "payload": {
    "onOff": false
  }
}
```

It will log an error letting you know that something may be wrong.
However, this doesn't necessarily have to cause any issues for you, since the node defaults back to the configuration. So if you've configured the node fully, it will work in spite of the errors.
