### ISSUE TITLE
Cannot set Temperature on older ikea bulbs

### ISSUE THREAD

**Issue by MajkCajk** [mjwwit/node-red-contrib-ikea-tradfri#4]
Hi, first of all, thank you for your great work 👍 .
I think that i tried everything, but couln't get my one ikea bulb to change temperature. Is it because of the older firmware (1.3.013)? Because the other (2.0.029) is changing just fine.

Thanks

**Comment by mjwwit** [comment]
If the newer firmware bulb is working fine I'm quite sure the firmware is the problem here. Can you not update the older firmware bulb?
Either way I recommend creating an issue [with the underlying library used by this project](https://github.com/AlCalzone/node-tradfri-client). I aim incorporate new releases of that library into this project as fast as possible.

**Comment by MajkCajk** [comment]
Unfortunately ikea app doesn't allow me to. I planning to buy a new one so this is another reason to do so. Thank you.
